from pathlib import Path

from pcse.crop.lintul_cassava10 import LINTUL_CASSAVA
from pcse.soil.lintul_cassava_soil_wrappers import Lintul_Cassava_WNLP_SoilWrapper
from pcse.agromanager import AgroManager

SOIL = Lintul_Cassava_WNLP_SoilWrapper
CROP = LINTUL_CASSAVA
AGROMANAGEMENT = AgroManager
OUTPUT_VARS = ["SM", "W", "RRD", "RD", "LAI", "WLVG", "WST", "WSO", "ANLVG", "ANST", "ANSO", "APLVG", "APST", "APSO", "AKLVG", "AKST", "AKSO", "RFTRA", 'NAVAIL', 'PAVAIL', 'KAVAIL', "NNI", "PNI", "KNI", "KNI", "NPKI", "REVAP", "RTRAN", "RPEVAP", "RPTRAN", "RFTRA"]
OUTPUT_INTERVAL = "daily"
OUTPUT_INTERVAL_DAYS = 1
OUTPUT_WEEKDAY = 0
SUMMARY_OUTPUT_VARS = ["WSO", "WLV", "WSO", "WST", "WRT", "TAGP", "RD", "LAIMAX", "TSUMCROP",
                       "ANLVG", "ANST", "ANSO", "APLVG", "APST", "APSO", "AKLVG", "AKST", "AKSO"]
TERMINAL_OUTPUT_VARS = []