from pathlib import Path

from pcse.crop.lintul_cassava10 import LINTUL_CASSAVA_NO_NUTRIENT_STRESS
from pcse.soil.lintul_cassava_soil_wrappers import Lintul_Cassava_WLP_SoilWrapper
from pcse.agromanager import AgroManager

SOIL = Lintul_Cassava_WLP_SoilWrapper
CROP = LINTUL_CASSAVA_NO_NUTRIENT_STRESS
AGROMANAGEMENT = AgroManager
OUTPUT_VARS = ["SM", "W", "RRD", "RD", "LAI", "WLVG", "WST", "WSO", "REVAP", "RTRAN", "RPEVAP", "RPTRAN", "RFTRA"]
OUTPUT_INTERVAL = "daily"
OUTPUT_INTERVAL_DAYS = 1
OUTPUT_WEEKDAY = 0
SUMMARY_OUTPUT_VARS = ["WSO", "WLV", "WSO", "WST", "WRT", "TAGP", "RD", "LAIMAX", "TSUMCROP", "CTRAT", "CEVST",
                       "DOS", "DOE", "DOH"]
TERMINAL_OUTPUT_VARS = []